### ISSUE TITLE
Using with Composer

### ISSUE THREAD

**Issue by timrogers** [sgotre/sphp-osx#10]
Is there any suggested practice or pattern for using `sphp-osx` with Composer?

**Comment by conradkleinespel** [comment]
@timrogers There shouldn't be anything holding you back from using both together. Have you had issues or conflicts between `sphp-osx` and `composer` ?

**Comment by timrogers** [comment]
I'll have a play with it. My concerns are probably unfounded!

**Comment by conradkleinespel** [comment]
@timrogers Sure, try and see if it works for you :) the goal of `sphp-osx` is to change PHP versions. Composer should work with all recent PHP versions (5.6/7), so you should be fine. If you run into problems though, please do file an issue so it can be resolved :+1:
