### ISSUE TITLE
Add list of installed PHP version

### ISSUE THREAD

**Issue by cbourgois** [sgotre/sphp-osx#11]
It will be useful to have the list of PHP installed versions in this script

```
$ sphp
Usage: sphp [phpversion]
Installed versions:
php56
php70
```

Maybe by adding 

```
brew list | grep '^php[0-9]\{2,\}$'
```

**Comment by sgotre** [comment]
Hi cbourgois, 

thank you very much for your proposal and pull request. I did not receive a notification about it :( But now i will have a look and merge if everything is ok. 

Thanks for contributing!

**Comment by sgotre** [comment]
feature is added
