### ISSUE TITLE
It's working, but...

### ISSUE THREAD

**Issue by iDGS** [sgotre/sphp-osx#15]
I'm using homebrew etc, and specifically your wonderful `sphp` to switch between php56, php70, and php71. (Mostly I'm parked in php70.)

After a bit of confusion with upgrading php's via `brew upgrade`, I now get this message whenever I restart apache after I switch to either php70 or php71 (but there's no problem after I switch to php56):
```
[~]$ sudo apachectl restart
[Sat Nov 26 11:57:20.120099 2016] [so:warn] [pid 6759] AH01574: module php7_module is already loaded, skipping
[Sat Nov 26 11:57:20.120312 2016] [so:warn] [pid 6759] AH01574: module php7_module is already loaded, skipping
```

Previously, at some point during my upgrade confusion it was only complaining on one line, but now it's complaining twice. How can I get rid of (both of) the complaint(s)?

Help?

**Comment by sgotre** [comment]
it seems like the entry there are several entries for php7_module in your httpd config. 
I will have to check php71 compatibility. Please give me some time.

**Comment by iDGS** [comment]
Sure thing. No problem waiting. Take your time.

Me? If I could've found the string, I'd've taken out the (two?) duplicates. I'm thinking there's three of them, hence the two "already loaded" messages. But, I can't find the string `php_module` anywhere except in `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php.rb` (which doesn't count). I suspect it may be hiding minified or in some other format in the likes of `/usr/local/Cellar/php70/7.0.13_6/libexec/apache2/libphp7.so`, etc. but that's beyond my reach. 

So, sure. I'd be delighted if you can track it down. Thankfully, it's not a show-stopper. Good luck!

**Comment by sgotre** [comment]
which apache do you use? homebrew or system apache?

**Comment by iDGS** [comment]
Homebrew, I think. How can I tell for sure?

**Comment by sgotre** [comment]
try `which httpd` and ` which apachectl`

**Comment by iDGS** [comment]
```
[~]$ which httpd
/usr/local/bin/httpd
[~]$ which apachectl
/usr/local/bin/apachectl
```

Does that help?

**Comment by iDGS** [comment]
Here's a little more info (I'm using mcrypt too):
```
[~]$ brew list
apr		git		libev		mhash		php70		unixodbc
apr-util	httpd24		libevent	nghttp2		php70-mcrypt	zlib
boost		icu4c		libpng		openssl		php71
doxygen		jansson		libtool		pcre		php71-mcrypt
freetype	jemalloc	libxml2		php56		readline
gettext		jpeg		mcrypt		php56-mcrypt	spdylay
[~]$ 
```

**Comment by sgotre** [comment]
ok, the entries are written to your httpd.conf file which you will find using `httpd -V`

**Comment by iDGS** [comment]
Ah. Thankyouthankyouthankyou!
Here's what I found in: `/usr/local/etc/apache2/2.4/httpd.conf`

```
...
# Brew PHP LoadModule for `sphp` switcher
#LoadModule php5_module /usr/local/lib/libphp5.so
LoadModule php7_module /usr/local/lib/libphp7.so
LoadModule php7_module        /usr/local/Cellar/php70/7.0.13_6/libexec/apache2/libphp7.so
LoadModule php7_module        /usr/local/Cellar/php71/7.1.0-rc.6_10/libexec/apache2/libphp7.so
...
```

Which should I delete?

**Comment by iDGS** [comment]
(I'm guessing "generic" and the php71 one, since I'm on php70 right now.) yes?

**Comment by iDGS** [comment]
Or I could just leave it alone. "'Cause if it ain't broke..." ("Don't 'fix it! LOL)

**Comment by sgotre** [comment]
ok, first make a copy of this file... an then delete the last 2.. but i am not 100% sure...
this is what mine is looking like:

`# Brew PHP LoadModule for `sphp` switcher
 #LoadModule php5_module /usr/local/lib/libphp5.so
 LoadModule php7_module /usr/local/lib/libphp7.so`

**Comment by sgotre** [comment]
the change in this file is only needed when switching between php 5 and php 7. 
The file /usr/local/lib/libphp7.so is kind of a symlink pointing to the correct php version you have choosen

**Comment by iDGS** [comment]
OK. Did as you suggested and took out the last two lines (after making a backup!), and all is well. Runs smooth, no complaints:
```
[~]$ sudo apachectl -k restart
Password:
[~]$ sphp 56
PHP version 56 found
Unlinking old binaries...
Linking new binaries...
Linking /usr/local/Cellar/php56/5.6.27_4... 17 symlinks created
Linking new modphp addon...
Fixing LoadModule...
Updating version file...
Restarting homebrew Apache...
Restarting non-root homebrew Apache...
Done.

PHP 5.6.27 (cli) (built: Oct 15 2016 13:28:07) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
[~]$ sudo apachectl -k restart
[~]$ sphp 70
PHP version 70 found
Unlinking old binaries...
Linking new binaries...
Linking /usr/local/Cellar/php70/7.0.13_6... 17 symlinks created
Linking new modphp addon...
Fixing LoadModule...
Updating version file...
Restarting homebrew Apache...
Restarting non-root homebrew Apache...
Done.

PHP 7.0.13 (cli) (built: Nov 26 2016 10:25:10) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
[~]$ sudo apachectl -k restart
[~]$ 
```

Thanks MUCH!

**Comment by sgotre** [comment]
great i could help ... enjoy it :)

**Comment by iDGS** [comment]
sgotre++ for solving my problem! (If this were Slack)
