### ISSUE TITLE
With PHP-FPM

### ISSUE THREAD

**Issue by esolitos** [sgotre/sphp-osx#18]
Hi, would you be interested into a PR to integrate the [php-fpm version of sphp](https://github.com/esolitos/sphp-fpm-osx) I recently wrote inspired by your awesome script?

**Comment by sgotre** [comment]
Hi, yes would be great! The script should check which servers are installed und then change the config files for all found servers, right?

**Comment by esolitos** [comment]
I was thinking to have a initial setup step, which lets you select which server are you using, but doinf as you describe seems a reasonable solution.
In the end it's a matter of calling 2 functions, not much more.

I'll see if I get some time soon and push a PR, if you want and have a few minutes take a look at the code I wrote in my fork and let me know if anything doesn't look right in your eyes _(read as: code that should not be like that in the PR)_ :)

**Comment by tholu** [comment]
@esolitos Just discovered your fork here, after I modified my fork to (minimally) support php-fpm. Would be nice to have this integrated in sphp!

**Comment by esolitos** [comment]
I've been working on some issues with some `dlyb` not loading correctly after the php version switch, been struggling a bit with this and haven't had time for a good PR.
I'll see this weekend if i get some time to handle this. :)

**Comment by tholu** [comment]
@esolitos I did not have issues when trying your fork, can you elaborate what happens for you regarding the `dlyb` loading?

**Comment by esolitos** [comment]
It's not always, I have not been able to debug exactly *when*, but sometimes on the php and php-fpm version swap there's something missing/not linked and i get errors.

Until now i had trouble with the following brew packages:
- php71-imagick (and related imagemagick)
- jpeg

The solution seems always to do a `brew remove --force --ignore-dependencies $package` and a `brew install`.

**Comment by esolitos** [comment]
I am not maintaining the sphp for fpm anymore, so i'll close this issue as i'm sure I won't be working on this.
