### ISSUE TITLE
Does not properly detect PHP versions anymore

### ISSUE THREAD

**Issue by tholu** [sgotre/sphp-osx#21]
Since homebrew migrated its PHP formulas, sphp does not properly detect any PHP versions anymore:

```
➜  sphp-osx git:(master) ./sphp
Usage: sphp [phpversion]
Versions installed:
➜  sphp-osx git:(master) brew list | grep '^php'
php
php@5.6
php@7.0
php@7.1
```

**Comment by sgotre** [comment]
thank you! I will test provide an update later.

**Comment by tholu** [comment]
@sgotre Thanks for your fast response!

I used this guide to fix my PHP installation after the homebrew migration:
https://getgrav.org/blog/macos-sierra-apache-multiple-php-versions

I found a working version of another sphp switcher here (linked in the guide): https://gist.githubusercontent.com/rhukster/f4c04f1bf59e0b74e335ee5d186a98e2/raw

**Comment by sgotre** [comment]
the script has some issues currently, but i did not have time to merge and fix :( 

thanks for the links, i will check and integrate if possible.
