### ISSUE TITLE
Homebrew

### ISSUE THREAD

**Issue by muuvmuuv** [sgotre/sphp-osx#25]
I think this script is pretty useful for all who are using PHP with homebrew, so it would be great if we could ship sphp with homebrew too.

**Comment by sgotre** [comment]
you have experience with that?

**Comment by muuvmuuv** [comment]
@sgotre no, sorry. I would need to read their docs too. I would suggest reading this issue and the PR's: https://github.com/stevegrunwell/asimov/issues/2
Not much time atm to make a PR by myself...

**Comment by sgotre** [comment]
@muuvmuuv not much time for me too :(
