### ISSUE TITLE
Support for PHP 5.4

### ISSUE THREAD

**Issue by nufrankz** [sgotre/sphp-osx#27]
Hello, thanks for this package.
I wonder if it's possible to install PHP 5.4 through SPHP?

I know I can download source from https://museum.php.net/php5/.
But I don't know the neccesary steps to make it work with SPHP.

Thank you!

**Comment by sgotre** [comment]
@nufrankz i am not using this script anymore. I can suggest laravel valet instead https://laravel.com/docs/5.8/valet

you can switch the php version much easier with valet.
valet use php@7.2 

https://gist.github.com/bgarrant/b9a2f7fb8ff06c9a45086359ded7a95e
