### ISSUE TITLE
Can not switch away from php70

### ISSUE THREAD

**Issue by sgotre** [sgotre/sphp-osx#7]
When php70 is active and i enter `$ sphp 56` there is an error: 
Is this caused by the deprecation warnings orr by "Error: Could not symlink bin/phar" 

I have to change LoadModule manually.
Any suggestions?

Thanks alot for the script!

```
PHP Deprecated:  PHP Startup: memcached.sess_lock_wait and memcached.sess_lock_max_wait are deprecated. Please update your configuration to use memcached.sess_lock_wait_min, memcached.sess_lock_wait_max and memcached.sess_lock_retries in Unknown on line 0
PHP Deprecated:  PHP Startup: memcached.sess_lock_wait and memcached.sess_lock_max_wait are deprecated. Please update your configuration to use memcached.sess_lock_wait_min, memcached.sess_lock_wait_max and memcached.sess_lock_retries in Unknown on line 0
PHP Deprecated:  PHP Startup: memcached.sess_lock_wait and memcached.sess_lock_max_wait are deprecated. Please update your configuration to use memcached.sess_lock_wait_min, memcached.sess_lock_wait_max and memcached.sess_lock_retries in Unknown on line 0
PHP Deprecated:  PHP Startup: memcached.sess_lock_wait and memcached.sess_lock_max_wait are deprecated. Please update your configuration to use memcached.sess_lock_wait_min, memcached.sess_lock_wait_max and memcached.sess_lock_retries in Unknown on line 0
PHP Deprecated:  PHP Startup: memcached.sess_lock_wait and memcached.sess_lock_max_wait are deprecated. Please update your configuration to use memcached.sess_lock_wait_min, memcached.sess_lock_wait_max and memcached.sess_lock_retries in Unknown on line 0
PHP Deprecated:  PHP Startup: memcached.sess_lock_wait and memcached.sess_lock_max_wait are deprecated. Please update your configuration to use memcached.sess_lock_wait_min, memcached.sess_lock_wait_max and memcached.sess_lock_retries in Unknown on line 0
PHP version 56 found
Unlinking old binaries...
Linking new binaries...
Linking /usr/local/Cellar/php56/5.6.19...
Error: Could not symlink bin/phar
Target /usr/local/bin/phar
is a symlink belonging to php70. You can unlink it:
  brew unlink php70

To force the link and overwrite all conflicting files:
  brew link --overwrite php56

To list all files that would be deleted:
  brew link --overwrite --dry-run php56
Linking new modphp addon...
ln: 5.so: No such file or directory
Fixing LoadModule...
sed: 1: "/LoadModule php
Depreca ...": unterminated regular expression
sed: 1: "/LoadModule php
Depreca ...": unterminated regular expression
Updating version file...
Restarting system Apache...
Done.

````

**Comment by conradkleinespel** [comment]
@sgotre Hello !

Thanks for taking the time to report this. You are awesome :smiley: 

Unfortunately, I am no longer maintaining this project, as I don't use OSX anymore. I'm sorry, because that means I can't help you with your issue.

Would you be interested in maintaining the project ? Or maybe someone else will know a way to solve your issue.

Best regards,
Conrad

**Comment by sgotre** [comment]
Hey Conrad,
Thanks for this incredible fast answer! :-) 

AS i will try to find a solution to my problem anyway i could take over this project if you want
Anything i have to know about it? :) 

best regards, 
stefan

**Comment by conradkleinespel** [comment]
@sgotre You are most welcome, Stefan ! :smiley: 

If you could find a solution, that would be awesome ! I don't think there is anything special that you should know to take over the project.

You can either fork, and I can point to your repo, or we can keep this repo up with a mention in the `README.md` that *you* are the maintainer. That way, the project keeps the star number and links don't get broken on the web (some blog posts have linked to this repo).

**I've given you commit access, so you can start pushing to this repository.**

Thank you so much for your help. I'm sure your work will benefit many OSX/PHP users !

Best regards,
Conrad

**Comment by sgotre** [comment]
Hi Conrad, 

ok thank you. You can transfer ownership. Al[l links will be redirected ](https://help.github.com/articles/transferring-a-repository/)

> When you transfer a repository, its issues, wiki, stars, and watchers are also transferred.

> 'When a repository is transferred, all links to the previous location are automatically redirected to the new location.'

So users will get the latest code even with old links. :) 
Please transfer it to the organization @teraone  - which is my company.

Best regards,
Stefan

**Comment by conradkleinespel** [comment]
@sgotre Oh, I didn't know that. Will do. Und ich wusste nicht, dass sie eine Deutsche Firma betreiben. Sehr schön ! :smiley: 

Just one small request, for both legal purposes and kindness : it would be good if contributor names stay in the `README.md` as they all hold copyright to the code they contributed and deserve credit.

**Comment by conradkleinespel** [comment]
@sgotre Woops, seems like I cannot transfer to an account I am not an admin of.

**Comment by sgotre** [comment]
hi conrad, 
hmm seems like you need to be member of @teraone .. no worries then just transfer it to me (@sgotre) !
I promise I will leave the credits! and copyright information! :+1: 

@conradkleinespel tu es a paris? j'aime paris :)

**Comment by conradkleinespel** [comment]
@sgotre Done ! Take good care of it :smiley: And thanks for your understanding regarding credits.

Oui, j'habite à Paris ! :)

**Comment by sgotre** [comment]
i'll do my very best! thanks again for creating this package!

**Comment by hellopablo** [comment]
@sgotre Is this something that you ever got to the bottom of?

**Comment by sgotre** [comment]
Yes. I had some startup errors in php. Thus it was not possible to get the current php version in the script. Make sure php -v does not give amy error.

**Comment by vreemt** [comment]
@hellopablo like @sgotre said, check php7 starts without errors. the memcached ones are posted here, including a solution: http://stackoverflow.com/questions/35130463/php7-memcache-deprecated-error-message (I had the same issue a while ago, but think it's been updated since then)

**Comment by sgotre** [comment]
Is there a console parameter to suppress startup errors? Could be handy to use it and catch these errors.

**Comment by vreemt** [comment]
on a command line when doing `php -v` you can do `php -n -v` as the `-n` suppresses _all_ *.ini files
when doing `php -r 'echo phpversion();` you can do `php -r 'error_reporting(0); echo phpversion(); '`

**Comment by vreemt** [comment]
see PR
